name: MoonlightPickaxes
version: 1.0
main: net.hylustpickaxes.src.Main
authors: [DepressedChan]
description: MoonlightPickaxes - Made by DepressedChan
depend: [PlaceholderAPI, Vault]
softdepend: [ShopGUIPlus, OreRegenerator, Quests]
commands:
  moonlightpickaxes:
    usage: /moonlightpickaxes
    description: Admin MoonlightPickaxes Command
  upgrade:
    usage: /upgrade
    description: Pickaxe Tool Upgrade Command
  tokens:
    usage: /tokens
    description: Tokens Command
    aliases: [token]